### ISSUE TITLE
Crash due missing parent dirs: _thermal_bwr./bwr

### ISSUE THREAD

**Issue by glensc** [nationaldronesau/FlirImageExtractor#15]
```
$ flir-image-extractor-cli
Processing the provided filepath...
 100.0% [=======================================================================================>]   4/  4 eta [00:00]
2022-08-06 19:03:54.540 | INFO     | flir_image_extractor_cli.__main__:main:104 - Processing the images...
2022-08-06 19:03:54.808 | SECTION  | flir_image_extractor_cli.processing:multiple_images:87 - Getting thermal information for all images
2022-08-06 19:03:55.629 | SECTION  | flir_image_extractor_cli.processing:multiple_images:110 - Processing and saving the images to disk
Traceback (most recent call last):
  File "/usr/local/bin/flir-image-extractor-cli", line 8, in <module>
    sys.exit(main())
  File "/usr/local/lib/python3.9/site-packages/flir_image_extractor_cli/__main__.py", line 105, in main
    processing.multiple_images(folder_path=path, palettes=palettes, custom_temperature=custom_temperature)
  File "/usr/local/lib/python3.9/site-packages/flir_image_extractor_cli/processing.py", line 114, in multiple_images
    flir.save_images(minTemp=dataset_min, maxTemp=dataset_max)
  File "/usr/local/lib/python3.9/site-packages/flir_image_extractor_cli/flir_image_extractor.py", line 442, in save_images
    img_thermal.save(filename, "jpeg", quality=100)
  File "/usr/local/lib/python3.9/site-packages/PIL/Image.py", line 2317, in save
    fp = builtins.open(filename, "w+b")
FileNotFoundError: [Errno 2] No such file or directory: '_thermal_bwr./bwr/flir_20220801T231233'

$ ls
_thermal./     Screenshot_20220801-231344.png  flir_20220801T231233.jpg
thermal-data/  Screenshot_20220801-231400.png  flir_20220801T231238.jpg

$
```

**Comment by glensc** [comment]
Workaround is to make those dirs, and retry.

**Comment by glensc** [comment]
More missing dirs

```
FileNotFoundError: [Errno 2] No such file or directory: '_thermal_bwr./bwr/flir_20220801T231233'
FileNotFoundError: [Errno 2] No such file or directory: '_thermal_gnuplot2./gnuplot2/flir_20220801T231233'
FileNotFoundError: [Errno 2] No such file or directory: '_thermal_gist_ncar./gist_ncar/flir_20220801T231233'
```

**Comment by williams9438** [comment]
fixed in the new version
